### ISSUE TITLE
Adding creatorFee to Niftyswap

### ISSUE THREAD

**Issue by pkieltyka** [0xsequence/niftyswap#42]
Almost all NFT exchanges allow for the creators to receive part of the trading fee, but Niftyswap currently doesn't.

As a V1, we could add two parameters in an exchange contract ; creatorFee and creatorAddress. The former is the % of fee that would go to the creator and the latter would be the address where these fees would be sent to. In order to prevent capture by front runners and such, these two parameters should be set by an operator.

Specifications:
- Only do this for the ERC20:ERC1155 contract
- Each exchange contract now need two new variables: `creatorAddress` and `creatorFee`. Both default to `0x0` on exchange creation
- These two variables **should only be set by the owner**. The owner should be the owner of the factory, passed down to the exchange contract on creation.
- **Only the owner** should be able to change the `creatorAddress` and `creatorFee`.
- When doing any trade (buy or sell), if `creatorFee is > 0`, an additional fee is charged in the ERC-20 currency and sent to the `creatorAddress`
- Adding or removing liquidity should **NOT** trigger a fee to be paid obviously.

**Comment by ScreamingHawk** [comment]
Niftyswap contracts do not currently support the `ownable` interface. Do you want this to be included in the change?

**Comment by PhABC** [comment]
> Niftyswap contracts do not currently support the `ownable` interface. Do you want this to be included in the change?

Yes that seems fine @ScreamingHawk !

**Comment by pkieltyka** [comment]
@ScreamingHawk are you working on this? we need to complete this task this week, so if you're busy, no prob and we will write it. Please ping us and we'll tackle it ourselves.

**Comment by ScreamingHawk** [comment]
Hey @pkieltyka , No sorry I haven't had a chance to pick this one up yet. Have a few other things on my plate I wanted to tidy up first.

**Comment by pkieltyka** [comment]
No prob at all, thank you anyways :) I just wanted to check so we didn’t dupe the effort
