### ISSUE TITLE
Updating solidity compiler version to ^0.8.0

### ISSUE THREAD

**Issue by TamirCohen** [0xsequence/niftyswap#54]
Currently the contracts (For example https://github.com/0xsequence/niftyswap/blob/master/src/contracts/exchange/NiftyswapExchange.sol) sepecifies the compier to be 
`pragma solidity 0.7.4;`
I was wandering If it can be upgraded to ^0.8.0 (Because Iam using this version in my project).

Thanks :)

**Comment by tonijarjour** [comment]
I would also appreciate an update to ^0.8.0

**Comment by pkieltyka** [comment]
cc: @ScreamingHawk :)

**Comment by ScreamingHawk** [comment]
In progress! 😁
