### ISSUE TITLE
TypeError: Member "buyTokens" not found or not visible after argument-dependent lookup in address

### ISSUE THREAD

**Issue by tonijarjour** [0xsequence/niftyswap#78]
Hi this is on  the `sol-update` branch

Heres some code:
```solidity
NiftyswapFactory20 internal immutable swapFactory;
...
//
// in constructor
//
swapFactory = new NiftyswapFactory20(address(this));
swapFactory.createExchange(address(this), WETH9, 10, 0);

uint256[] memory amount = new uint256[](1);
amount[0] = 10000000000;

bytes memory data = abi.encode(
    ADDLIQUIDITY_SIG,
    AddLiquidityObj(amount, block.timestamp + SECONDS_DEADLINE)
);

safeBatchTransferFrom(
    address(this),
    address(swapFactory),
    tokenID,
    amount,
    data
);

...
// in a function for buying the token
swapFactory.getPairExchanges(address(this), WETH9)[0].buyTokens(...);
```
This last line errors with this:
```
TypeError: Member "buyTokens" not found or not visible after argument-dependent lookup in address.
```

I'd just like to know how to fix it.

**Comment by ScreamingHawk** [comment]
Hi @tonijarjour . The branch did not have updated build artifacts at the time you raised this ticket. Can you please try again now the branch has been merged and see if this is still an issue?

**Comment by tonijarjour** [comment]
This same error message persists.

**Comment by ScreamingHawk** [comment]
Sorry about that @tonijarjour 

`swapFactory.getPairExchanges(address(this), WETH9)...` will return the list of exchanges by `lp_fee` and `instance`. 
Replace this with:
`swapFactory.tokensToExchange(address(this), WETH9, 10, 0)...`
This will get the exchange you created using the params in `swapFactory.createExchange`. 
You'll need to cast the address to the an INiftyswapExchange20 type as well. 

We now have some foundry tests which you may find useful as references. 

https://github.com/0xsequence/niftyswap/blob/master/tests_foundry/NiftyswapExchange20.test.sol#L74

**Comment by ScreamingHawk** [comment]
Closing this ticket due to lack of response. Please reopen if you are still having issues @tonijarjour
